# Generated by Django 2.2.7 on 2019-11-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_names', models.CharField(max_length=30)),
                ('actor_names', models.CharField(max_length=30)),
            ],
        ),
    ]
